project_id = "lczzyelucnfvkicwdbbe"

[functions.recommend-listings]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = false

[functions.confirm-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-inactive-listing-reminder]
verify_jwt = false

[functions.geocode-listings]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.notify-new-message]
verify_jwt = false

[functions.notify-new-follower]
verify_jwt = false

[functions.notify-new-review]
verify_jwt = false

[functions.notify-new-favorite]
verify_jwt = false

[functions.notify-price-offer]
verify_jwt = false

[functions.notify-new-listing]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
