project_id = "lczzyelucnfvkicwdbbe"

[functions.recommend-listings]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = false

[functions.confirm-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false