project_id = "lczzyelucnfvkicwdbbe"

[functions.recommend-listings]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = false

[functions.confirm-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-inactive-listing-reminder]
verify_jwt = false

[functions.geocode-listings]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false